linters:
  disable-all: true
  enable:
    - gci
    - goconst
    - errcheck
    - gosimple
    - govet
    - copyloopvar
    - cyclop
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - prealloc
    - predeclared
    - reassign
    - revive
    - stylecheck
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - blank
      - default
      - blank
      - localmodule