// Code generated by mockery v2.42.1. DO NOT EDIT.

package mockery

import mock "github.com/stretchr/testify/mock"

// MockInPackageTools is an autogenerated mock type for the InPackageTools type
type MockInPackageTools struct {
	mock.Mock
}

type MockInPackageTools_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInPackageTools) EXPECT() *MockInPackageTools_Expecter {
	return &MockInPackageTools_Expecter{mock: &_m.Mock}
}

// String provides a mock function with given fields:
func (_m *MockInPackageTools) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockInPackageTools_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockInPackageTools_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockInPackageTools_Expecter) String() *MockInPackageTools_String_Call {
	return &MockInPackageTools_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockInPackageTools_String_Call) Run(run func()) *MockInPackageTools_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInPackageTools_String_Call) Return(_a0 string) *MockInPackageTools_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInPackageTools_String_Call) RunAndReturn(run func() string) *MockInPackageTools_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInPackageTools creates a new instance of MockInPackageTools. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInPackageTools(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInPackageTools {
	mock := &MockInPackageTools{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
